### ISSUE TITLE
有报错，不清楚具体原因

### ISSUE THREAD

**Issue by JefferyLi0903** [FDUCSLG/pafd-automated#18]
![image](https://user-images.githubusercontent.com/31439283/141718095-b4359312-aa9a-4b49-821c-b20030e9b73d.png)
错误如图所示。
[error.log](https://github.com/FDUCSLG/pafd-automated/files/7535694/error.log)

**Comment by SunflowerAries** [comment]
有参照 README 设置 STD_ID 相关的信息么？

**Comment by JefferyLi0903** [comment]
嗯，设置了。

**Comment by JefferyLi0903** [comment]
谢谢，我是试试看
