### ISSUE TITLE
今天突然报错

### ISSUE THREAD

**Issue by NeamZhang** [FDUCSLG/pafd-automated#20]
![Screenshot_20211230_094158](https://user-images.githubusercontent.com/73150263/147715106-3417db20-296e-449a-b2e9-4c364753a229.jpg)
已经用了两个月都没有问题，但在今天早上突然收到报错，重新运行几次都卡在了98.4%处，报错139，代码应该没有变化，怎么解决呢？

**Comment by Saul-Song** [comment]
同样的报错

**Comment by eslgf** [comment]
同，exit code 139报错

**Comment by www1ball1n** [comment]
同139

**Comment by eslgf** [comment]
回上，主页有教程更新一下fork就可以了

**Comment by www1ball1n** [comment]
> 回上，主页有教程更新一下fork就可以了

![image](https://user-images.githubusercontent.com/61548672/147718264-1e057f17-b75b-44c1-880f-9a3dca84aba0.png)
点过了 照理应该没问题啊

**Comment by cilebritain** [comment]
同报错，这个repo不是最近都没有commit吗，之前fork的版本就是latest才对

**Comment by Xin200203** [comment]
应该是都出现了问题，更新fork貌似不行

**Comment by autumnalK** [comment]
我换了一个验证码识别的库，目前是执行成功的，开了个pull request，有需要可以自取
