### ISSUE TITLE
build - run 运行失败

### ISSUE THREAD

**Issue by bluebread** [FDUCSLG/pafd-automated#34]
报错信息：

Run STD_ID=*** *** python3 main.py
  STD_ID=*** *** python3 main.py
  shell: /usr/bin/bash -e {0}
从环境变量中获取了用户名和密码！
◉Initiating——return status code 200
◉Initiated——getting tokens
◉Login ing——return status code 302

***********************
◉登录成功
***********************

◉检测是否已提交
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    daily_fudan.check()
  File "main.py", line 146, in check
    print("◉上一次提交日期为:", last_info["d"]["info"]["date"])
TypeError: 'bool' object is not subscriptable
Error: Process completed with exit code 1.

不知道有没有其他同学遇到相似的问题。

**Comment by phourior** [comment]
+1，我也遇到了这种情况，前一天还是正常运行的

**Comment by bluebread** [comment]
自己查出来了，重新手动填写后隔一天就会恢复正常。原因是 last_info["d"]["info"] 是上一次填写的内容，如果你有哪一次中断了没填，系统返回请求 last_info["d"]["info"] 是 false 所以才会报错。
