### ISSUE TITLE
UNSAFE_LEGACY_RENEGOTIATION_DISABLED

### ISSUE THREAD

**Issue by Aurora-ma** [FDUCSLG/pafd-automated#51]
requests.exceptions.SSLError: HTTPSConnectionPool(host='zlapp.fudan.edu.cn', port=443): Max retries exceeded with url: /ncov/wap/fudan/get-info (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))

**Comment by Aurora-ma** [comment]
<img width="623" alt="微信截图_20221130133539" src="https://user-images.githubusercontent.com/117069463/204716104-28c0a594-6434-4cd9-ac2c-5f87dc2197f9.png">

**Comment by MengAaron** [comment]
我也遇到了
